# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Collections
# collections:
#  research:
#    output: true
#    permalink: /research/:path/

# Setup
title:            Design docs
tagline:          'Test idea'
description:      'Testing out a simple site for design documentation.'
url:              https://18f.github.io/test-docsite
baseurl:          https://18f.github.io/test-docsite

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://18f.github.io/test-docsite/
